#!/bin/bash
#Set variables

#I heavily recommend to set the variables in the template

#APP_NAME=radarr
#DOCKER_MODS=ghcr.io/gilbn/theme.park:${APP_NAME}
#TP_DOMAIN=theme-park.dev
#TP_THEME=organizr-dark
#TP_ADDON=radarr-4k-logo
APP_FILEPATH="${DATA_DIR}/Radarr/UI/index.html"

if ! grep -q "#theme.park integration" /opt/scripts/start-server.sh; then
    sed -i '/^echo "---Starting .*/i\#theme.park integration \
if ! grep -q \"'${TP_DOMAIN}'\" '$APP_FILEPATH'; then \
    if [ ! -f \"'${APP_FILEPATH}'.old\" ]; then \
        cp '${APP_FILEPATH}' '${APP_FILEPATH}'.old \
    fi \
    sed -i "s/<\\\\/head>/<link rel=stylesheet href=https:\\\/\\\/'${TP_DOMAIN}'\\\/CSS\\\/themes\\\/radarr\\\/'${TP_THEME}'.css><\\\\/head>/g" '${APP_FILEPATH}' \
fi \
' /opt/scripts/start-server.sh
elif ! grep -q "${TP_THEME}" /opt/scripts/start-server.sh; then
        cp ${APP_FILEPATH}.old ${APP_FILEPATH}
        rm -rf ${APP_FILEPATH}.old
        sed -i '/#theme.park integration/,+4d' /opt/scripts/start-server.sh
        sed -i '/^echo "---Starting .*/i\#theme.park integration \
if ! grep -q \"'${TP_DOMAIN}'\" '$APP_FILEPATH'; then \
    if [ ! -f \"'${APP_FILEPATH}'.old\" ]; then \
        cp '${APP_FILEPATH}' '${APP_FILEPATH}'.old \
    fi \
    sed -i "s/<\\\\/head>/<link rel=stylesheet href=https:\\\/\\\/'${TP_DOMAIN}'\\\/CSS\\\/themes\\\/radarr\\\/'${TP_THEME}'.css><\\\\/head>/g" '${APP_FILEPATH}' \
fi \
' /opt/scripts/start-server.sh
fi
exit
